paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        "200":
          $ref: "#/components/GoodResponses/GetAllProductsResponse"

    post:
      tags:
        - Products
      summary: Create an product
      requestBody:
        $ref: "#/components/RequestBodies/CreateProductRequest"
      responses:
        "201":
          $ref: "#/components/GoodResponses/CreateProductResponse"
        "400":
          $ref: "#/components/BadResponses/BadRequestResponse"
        "409":
          $ref: "#/components/BadResponses/DuplicateKeyResponse"
        "422":
          $ref: "#/components/BadResponses/ValidationErrorResponse"
  
  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Get product by PID (Product ID)
      parameters:
        - $ref: "#/components/Parameters/PidPathParam"
      responses:
        "200":
          $ref: "#/components/GoodResponses/GetProductByIdResponse"
        "404":
          $ref: "#/components/BadResponses/NotFoundResponse"

    put:
      tags:
        - Products
      summary: Update product by PID (Product ID)
      parameters:
        - $ref: "#/components/Parameters/PidPathParam"
      requestBody:
        $ref: "#/components/RequestBodies/UpdateProductRequest"
      responses:
        "200":
          $ref: "#/components/GoodResponses/UpdateProductResponse"
        "404":
          $ref: "#/components/BadResponses/NotFoundResponse"

    delete:
      tags:
        - Products
      summary: Delete product by PID (Product ID)
      parameters:
        - $ref: "#/components/Parameters/PidPathParam"
      responses:
        "200":
          $ref: "#/components/GoodResponses/DeleteProductResponse"
        "404":
          $ref: "#/components/BadResponses/NotFoundResponse"

  /api/products/available:
    get:
      tags:
        - Products
      summary: Get all available products
      responses:
        "200":
         $ref: "#/components/GoodResponses/GetAvailableProductsResponse"
        
        